### ISSUE TITLE
create-sample-dapp

### ISSUE THREAD

**Issue by krungle-mataman** [BboyAkers/simple-dapp-tutorial#33]
hello,
i just try to continue the "create-simply-dapp" tuturial and - as far i understand - metamask is not injection web3 anymore. But why is piggybank using web3 definitions ?

i found out that after deploying a new contract you using the web3.eth.contract - why

p.s. my goal is to get a contract-object (i still got the adress) and calling functions from the contract !

**Comment by BboyAkers** [comment]
Thanks for pushing this out. I'll have to change that 🙂!

**Comment by krungle-mataman** [comment]
thanks
